// <auto-generated />
using System;
using Academy.Week4.EntityFramework.Es1.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Academy.Week4.EntityFramework.Es1.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Academy.Week4.EntityFramework.Es1.Entities.Azienda", b =>
                {
                    b.Property<int>("AziendaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AziendaID"), 1L, 1);

                    b.Property<int>("AnnoFondazione")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AziendaID");

                    b.ToTable("Azienda");
                });

            modelBuilder.Entity("Academy.Week4.EntityFramework.Es1.Entities.Impiegato", b =>
                {
                    b.Property<int>("ImpiegatoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImpiegatoID"), 1L, 1);

                    b.Property<int>("AziendaID")
                        .HasColumnType("int");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataDiNascita")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImpiegatoID");

                    b.HasIndex("AziendaID");

                    b.ToTable("Impiegato");
                });

            modelBuilder.Entity("Academy.Week4.EntityFramework.Es1.Entities.Impiegato", b =>
                {
                    b.HasOne("Academy.Week4.EntityFramework.Es1.Entities.Azienda", "Azienda")
                        .WithMany("Impiegati")
                        .HasForeignKey("AziendaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Azienda");
                });

            modelBuilder.Entity("Academy.Week4.EntityFramework.Es1.Entities.Azienda", b =>
                {
                    b.Navigation("Impiegati");
                });
#pragma warning restore 612, 618
        }
    }
}
